language: objective-c
cache: cocoapods
xcode_workspace: MIST.xcworkspace
xcode_scheme: MIST
osx_image: xcode9.4
xcode_sdk: iphonesimulator
branches:
  only:
  - master
rvm: 2.4.1
before_install:
  - gem install cocoapods -v '1.5.3'
  
