language: objective-c
cache: 
  - cocoapods
  - bundler
xcode_workspace: MIST.xcworkspace
xcode_scheme: MIST
osx_image: xcode9.4
xcode_sdk: iphonesimulator
branches:
  only:
  - master
before_install:
- rvm install ruby-2.4.1
- gem update cocoapods
- pod repo update > /dev/null
