language: objective-c
cache: cocoapods
xcode_workspace: MIST.xcworkspace
xcode_scheme: MIST
osx_image: xcode9.4
xcode_sdk: iphonesimulator
rvm: 1.9.3
branches:
  only:
  - master
before_install:
  - pod repo update > /dev/null
  
