language: objective-c
xcode_scheme: MIST
osx_image: xcode9.4
xcode_sdk: iphonesimulator
branches:
  only:
  - master
before_install:
  - gem install cocoapods
  - pod setup --silent
  - pod repo update --silent
script:
  - pod install
  - xcodebuild -workspace MIST.xcworkspace -scheme MIST -sdk iphonesimulator
  
