# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MIST-Demo' do
  
  pod 'SDWebImage'
  pod 'IDMPhotoBrowser'
  pod 'MIST', :path => '../'
  pod 'MISTDebug', :configurations => ['Debug']

end
